apiVersion: v1
kind: Template
metadata:
  name: selenium-node-firefox
  annotations:
    description: "Selenium Node with Google firefox browser"
    iconClass: "icon-selenium"
    tags: "selenium,node,firefox"
objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    labels:
      app: selenium
      service: selenium-node-firefox
      build: selenium-node-firefox
    name: selenium-node-firefox
  spec:
    triggers:
    - type: ConfigChange
      configChange: {}
    source:
      contextDir: selenium-node-firefox
      type: Git
      git:
        uri: ${GIT_URI}
        ref: ${GIT_REF}
    strategy:
      type: Docker
      DockerStrategy:
        from:
          kind: "DockerImage"
          name: "selenium/node-firefox:${VERSION}"
    output:
      to:
        kind: ImageStreamTag
        name: selenium-node-firefox-ocp:${VERSION}
- kind: ImageStream
  apiVersion: v1
  metadata:
    labels:
      app: selenium
      build: selenium-node-firefox
    name: selenium-node-firefox-ocp
  spec: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: selenium
      service: selenium-node-firefox
    name: selenium-node-firefox
  spec:
    strategy:
      type: Recreate
    replicas: 1
    selector:
      app: selenium
      service: selenium-node-firefox
      browser: firefox
    template:
      metadata:
        name: selenium-node-firefox-master
        labels:
          app: selenium
          service: selenium-node-firefox
          browser: firefox
      spec:
        containers:
        - env:
          - name: JAVA_OPTS
            value: ${JAVA_OPTS}
          - name: SE_OPTS
            value: ${SE_OPTS}
          - name: HUB_PORT_4444_TCP_ADDR
            value: ${HUB_PORT_4444_TCP_ADDR}
          - name: HUB_PORT_4444_TCP_PORT
            value: ${HUB_PORT_4444_TCP_PORT}
          - name: REMOTE_HOST
            value: ${REMOTE_HOST}
          image: ""
          name: master
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 5555
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: ${RESOURCES_LIMIT_CPU}
              memory: ${RESOURCES_LIMIT_MEMORY}
          ports:
          - containerPort: 4444
            protocol: TCP
          - containerPort: 5555
            protocol: TCP
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - master
        from:
          kind: ImageStreamTag
          name: selenium-node-firefox-ocp:${VERSION}
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: selenium
      service: selenium-node-firefox
    name: selenium-node-firefox
  spec:
    selector:
      app: selenium
      service: selenium-node-firefox
      browser: firefox
    type: ClusterIP
    ports:
    - name: node-port
      port: 5555
      targetPort: 5555
      protocol: TCP
    - name: node-port-grid
      port: 4444
      targetPort: 4444
      protocol: TCP
parameters:
- name: JAVA_OPTS
  description: Options for the Java command
  value: "-Xmx512m -Dselenium.LOGGER.level=WARNING"
- name: SE_OPTS
  description: Options for the Node
  value: ""
- name: HUB_PORT_4444_TCP_ADDR
  description: The Hub to connect to
  value: "selenium-hub"
- name: HUB_PORT_4444_TCP_PORT
  description: The Hub port to connect to
  value: "4444"
- name: REMOTE_HOST
  description: The remote host
  value: ""
- name: NODE_ID
  description: Unique ID assigned to the node
  generate: expression
  from: '[a-z]{4}'
- name: RESOURCES_LIMIT_CPU
  description: Resources limit CPU
  value: "1000m"
- name: RESOURCES_LIMIT_MEMORY
  description: Resources limit memory
  value: "512Mi"
- name: VERSION
  description: Grid Selenium version
  value: "3.8.1"
- name: GIT_URI
  description: Git URI
  value: https://github.com/arnaud-deprez/selenium-openshift-templates.git
- name: GIT_REF
  description: Git ref, branch or tag
  value: master