{{- if and (eq "openshift" .Values.deployment.type) (.Values.selenium.chrome.enabled) -}}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
{{ include "selenium.labels" . | indent 4 }}
    build: selenium
  name: {{ regexSplit "/" .Values.selenium.chrome.image -1 | last | quote }}
spec: {}
{{- end }}