{{- if and (.Values.ingress.enabled) -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
{{ include "selenium.labels" . | indent 4 }}
  annotations:
    template.openshift.io/expose-uri: http://{.spec.host}{.spec.path}
{{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
  name: {{ template "selenium.hub.fullname" . }}
spec:
  rules:
  - host: {{ .Values.ingress.hostname | quote }}
    http:
      paths:
      - backend:
          serviceName: {{ template "selenium.hub.fullname" . }}
          servicePort: hub
        path: {{ .Values.ingress.path }}
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end }}
{{- end }}